---
apiVersion: v1
kind: Service
metadata:
  name: "drunken-lizards"
  labels:
    app: "drunken-lizards"
    tier: "frontend"
spec:
  type: "LoadBalancer"
  selector:
    app: "drunken-lizards"
    tier: "frontend"
  ports:
    - port: 80
      targetPort: 8000
