---
apiVersion: v1
kind: ReplicationController
metadata:
  generateName: drunken-lizards-
  labels:
    app: drunken-lizards
    tier: "frontend"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drunken-lizards
        tier: "frontend"
    spec:
      containers:
        - name: "drunken-lizards"
          image: "gcr.io/drunken-lizards/drunken-lizards:${DRUNKEN-LIZARDS_TAG}"
          env:
            - name: NODE_ENV
              value: "production"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
              protocol: "TCP"
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "1Gi"
      restartPolicy: "Always"
